version: "3.6"
services:
  web:
  # 是用craftcms官方的nginx 和 cms镜像
    image: craftcms/nginx:8.0-dev
    #映射本地端口8080
    ports:
      - 8080:8080
    env_file: .env
    environment:
      XDEBUG_CONFIG: client_host=host.docker.internal
    #mysql和redis跑起来后才会跑craftcms 
    depends_on:
      - mysql
      - redis
    #映射docker内容到本地，本地和docker文件会互相更新。
    volumes:
      - .:/app
    networks:
            - craft-demo-network

  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_USER: craft
       MYSQL_PASSWORD: password
       MYSQL_DATABASE: craft_demo
    #映射和保存数据库内容到本地，docker会自动挂载和管理
    volumes:
      - db_data:/var/lib/mysql
    networks:
            - craft-demo-network

  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

volumes:
  db_data:


networks:
    craft-demo-network:
