field: f4e04a1a-8e97-407a-a137-3d9a63e828d2 # Post Content
fieldLayouts:
  0673b017-5a70-44b1-b8ab-3b836b0b251e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 399e1119-51ea-424e-8d3f-49603879937d # Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c52c3a3e-d9ee-416f-a4ef-2458088160d3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3bc1f86c-beab-4917-a849-a27ac1458368
        userCondition: null
fields:
  399e1119-51ea-424e-8d3f-49603879937d: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:fb716acc-937f-4b8f-860b-bb3787452511' # s3demo
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: true
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:ceedbeea-3ded-4a15-a2f6-8ad473b1e530' # blog
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: image
name: Image
sortOrder: 2
