defaultPlacement: end
fieldLayouts:
  fff2f6e3-7287-4ed8-bece-77353d2d738b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 939f7517-b750-4746-8285-61462d05b092
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 63760053-77af-4db6-9436-1685d5cbe656
        userCondition: null
handle: bolgCategory
name: 'bolg category'
siteSettings:
  fc128974-a05c-49cf-97d7-b81049482356: # craftcms
    hasUrls: true
    template: blog/_category
    uriFormat: 'bolg-category/{slug}'
structure:
  maxLevels: 1
  uid: 250dd096-6c2a-45f5-8a22-c549ba019942
