columnSuffix: null
contentColumnType: string
fieldGroup: 86f844ec-4670-4430-95ad-c346aef4a8c9 # blog post fields
handle: featureimage
instructions: null
name: featureimage
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:ceedbeea-3ded-4a15-a2f6-8ad473b1e530' # blog
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maxRelations: null
  minRelations: 1
  previewMode: full
  restrictFiles: true
  restrictLocation: true
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:ceedbeea-3ded-4a15-a2f6-8ad473b1e530' # blog
  restrictedLocationSubpath: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Asset
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\assets\AssetCondition
  selectionLabel: null
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  source: null
  sources:
    - 'volume:ceedbeea-3ded-4a15-a2f6-8ad473b1e530' # blog
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
