columnSuffix: null
contentColumnType: string
fieldGroup: 86f844ec-4670-4430-95ad-c346aef4a8c9 # blog post fields
handle: postContent
instructions: null
name: 'Post Content'
searchable: false
settings:
  contentTable: '{{%matrixcontent_postcontent}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
