columnSuffix: null
contentColumnType: string
fieldGroup: 86f844ec-4670-4430-95ad-c346aef4a8c9 # blog post fields
handle: postcategory
instructions: null
name: postcategory
searchable: false
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: false
  source: 'group:29dc2492-a917-415b-a597-c54cf3af6a01' # bolg category
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
